### ISSUE TITLE
Section on what to do after installing

### ISSUE THREAD

**Issue by micho** [shamirlabs/docs#10]
Right now the installation guide ends in [Register your node](https://docs.shamirlabs.org/testnet/install/register).

The next section is [Update Diva](https://docs.shamirlabs.org/testnet/update-diva), and then Known Bugs

I propose to add a new section before or after Update Diva called:

**Setup complete: what's next?**

possible content:

- explain how they'll be receiving keyshares
- explain how to maintain the node
- link to divascan to inspect the internals
- ask to join the operator testnet channels

thoughts? anything else?

**Comment by micho** [comment]
cc @pradavc @actuallymentor @yorickdowne

**Comment by pradavc** [comment]
Ok, so you commented about what I see are 3 different things:
- How to maintain a node and update Diva concerns information about post-installation, which I think makes sense, and can be in a separated section after install. Howerver, I am struggling to see where to put the extended doc for the scripts, because there are more options that need code and doc. Such doc should be then referenced in this proposed section.
- Information about receiving key shares etc should be mostly part of the specs (which are completely empty as of now). I would keep this topic in a separated issue, opened, that depends on enhanced specs and cannot be closed without it. So in summary: create one new issue about "Documentation about the creation of distributed validators" that should be referenced in the post-installation section.
- Divascan is also a good reference, but I see it as "tools" or "references" that people should check after installation. It is related to the first point, but should also be in a separated section where we collect all the resources.

**Comment by micho** [comment]
> How to maintain a node and update Diva concerns information about post-installation

I agree, want me to make a PR with instructions in its own section? Before or after Update Diva? I'd do an initial PR with the goal of improving it with your input

**Comment by micho** [comment]
> Information about receiving key shares etc should be mostly part of the specs

Assuming specs are still going to take time, I think it's important to have even a brief mention of what to do next. As the Operator UX isn't self-explanatory at the moment, and there is no reference of it outside Discord

In its final version, the post-install section should include a 1-2 line explanation + link to full details in its own section

**Comment by micho** [comment]
> Divascan is also a good reference, but I see it as "tools" or "references" 

I can start a section for Diva Resources at the bottom of the sidebar. Would add general a Testnet section including the Shamir repos + Divascan, and other sections for completeness.

Do you also want to add things like deployed Goerli SCs?

**Comment by micho** [comment]
Other suggestions I've been collecting:

- How to access API
- Examples of dashboards like Dune with example queires: https://dune.com/kevinzzz/diva-testnet-operation-status
- Explain how to get validators (no collateral now, need collateral later)
- View Divascan
- Sign up for announcements on Discord
- Contribute to docs or repo
- Docker commands, like:

```
# You can see the sync proces calling the log command of your consensus and execution layer like this:
docker logs -f beacon       # for prysm
docker logs -f geth         # for geth

docker stop diva
docker start diva
```

**Comment by pradavc** [comment]
All these are good ideas. 

If you want to create a PR for each listed topic, please do so. I think the `Setup complete: what's next?` would help already.

**Comment by micho** [comment]
The issue with not knowing what to do to receive keyshares persists. Should start documenting that

<img width="470" alt="image" src="https://github.com/shamirlabs/docs/assets/323401/4fe09390-807a-4ab3-a706-211e789ad298">

**Comment by micho** [comment]
Checking version:

![Screenshot 2023-09-25 at 23 46 51](https://github.com/shamirlabs/docs/assets/323401/f620cb00-6ef2-4a40-9856-e78794c10b08)

**Comment by micho** [comment]
implemented! created new issues

- https://github.com/shamirlabs/docs/issues/13 
- https://github.com/shamirlabs/docs/issues/27
